// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rjlmiqbnfqfozucyhcbb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqbG1pcWJuZnFmb3p1Y3loY2JiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyMDE5NzgsImV4cCI6MjA3MDc3Nzk3OH0.SORxgV1pTVWe9gedpjQrwzv-L2dyGNVQxQLXz13Ek_A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});